using ClipboardUtility.src.Helpers;
using ClipboardUtility.src.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Text.Json;

namespace ClipboardUtility.src.Services
{
    /// <summary>
    /// Service for loading license information from JSON files generated by dotnet-project-licenses.
    /// </summary>
    public class LicenseLoaderService
    {
        private const string LicenseFileName = "licenses.json";

        /// <summary>
        /// Loads package license information from the licenses.json file.
        /// </summary>
        /// <returns>List of license info, or empty list if file not found or error occurs.</returns>
        public IReadOnlyList<LicenseInfo> LoadPackageLicenses()
        {
            try
            {
                var baseDir = AppDomain.CurrentDomain.BaseDirectory ?? string.Empty;
                var licensePath = Path.Combine(baseDir, LicenseFileName);

                Debug.WriteLine($"LicenseLoaderService: Looking for licenses at {licensePath}");

                if (!File.Exists(licensePath))
                {
                    Debug.WriteLine($"LicenseLoaderService: {LicenseFileName} not found");
                    return Array.Empty<LicenseInfo>();
                }

                var jsonContent = File.ReadAllText(licensePath);
                var licenses = JsonSerializer.Deserialize<List<LicenseInfo>>(jsonContent);

                if (licenses == null)
                {
                    Debug.WriteLine("LicenseLoaderService: Deserialization returned null");
                    return Array.Empty<LicenseInfo>();
                }

                Debug.WriteLine($"LicenseLoaderService: Loaded {licenses.Count} package license(s)");
                return licenses;
            }
            catch (JsonException ex)
            {
                Debug.WriteLine($"LicenseLoaderService: JSON parse error - {ex.Message}");
                FileLogger.LogException(ex, "LicenseLoaderService.LoadPackageLicenses: JSON parse error");
                return Array.Empty<LicenseInfo>();
            }
            catch (Exception ex)
            {
                Debug.WriteLine($"LicenseLoaderService: Error loading licenses - {ex.Message}");
                FileLogger.LogException(ex, "LicenseLoaderService.LoadPackageLicenses");
                return Array.Empty<LicenseInfo>();
            }
        }

        /// <summary>
        /// Loads font license files (OFL.txt) from the output directory.
        /// </summary>
        /// <returns>Dictionary with font name as key and license content as value.</returns>
        public IReadOnlyDictionary<string, string> LoadFontLicenses()
        {
            var result = new Dictionary<string, string>();

            try
            {
                var baseDir = AppDomain.CurrentDomain.BaseDirectory ?? string.Empty;

                if (!Directory.Exists(baseDir))
                {
                    Debug.WriteLine("LicenseLoaderService: Base directory does not exist");
                    return result;
                }

                var foundFiles = Directory.EnumerateFiles(baseDir, "OFL.txt", SearchOption.AllDirectories);

                foreach (var file in foundFiles)
                {
                    try
                    {
                        string title = Path.GetFileName(Path.GetDirectoryName(file)) ?? Path.GetFileName(file);
                        string content = File.ReadAllText(file, System.Text.Encoding.UTF8);
                        result[title] = content;
                        Debug.WriteLine($"LicenseLoaderService: Loaded font license for {title}");
                    }
                    catch (Exception ex)
                    {
                        Debug.WriteLine($"LicenseLoaderService: Error loading font license from {file}: {ex.Message}");
                    }
                }

                Debug.WriteLine($"LicenseLoaderService: Loaded {result.Count} font license(s)");
            }
            catch (Exception ex)
            {
                Debug.WriteLine($"LicenseLoaderService: Error searching for font licenses - {ex.Message}");
                FileLogger.LogException(ex, "LicenseLoaderService.LoadFontLicenses");
            }

            return result;
        }
    }
}
