//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClipboardUtility.src.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClipboardUtility.src.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CancelText {
            get {
                return ResourceManager.GetString("CancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   NotificationDuration に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotificationDurationTitle {
            get {
                return ResourceManager.GetString("NotificationDurationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Whitespace collapsed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotificationFormat_CollapseWhitespace {
            get {
                return ResourceManager.GetString("NotificationFormat_CollapseWhitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tabs converted to spaces に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotificationFormat_ConvertTabsToSpaces {
            get {
                return ResourceManager.GetString("NotificationFormat_ConvertTabsToSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copied {0} characters に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotificationFormat_CopiedWords {
            get {
                return ResourceManager.GetString("NotificationFormat_CopiedWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lines joined with spaces に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotificationFormat_JoinLinesWithSpace {
            get {
                return ResourceManager.GetString("NotificationFormat_JoinLinesWithSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Line breaks removed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotificationFormat_LineBreakRemoved {
            get {
                return ResourceManager.GetString("NotificationFormat_LineBreakRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Text normalized に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotificationFormat_NormalizeUnicode {
            get {
                return ResourceManager.GetString("NotificationFormat_NormalizeUnicode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Control characters removed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotificationFormat_RemoveControlChars {
            get {
                return ResourceManager.GetString("NotificationFormat_RemoveControlChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Diacritics removed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotificationFormat_RemoveDiacritics {
            get {
                return ResourceManager.GetString("NotificationFormat_RemoveDiacritics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Duplicate lines removed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotificationFormat_RemoveDuplicateLines {
            get {
                return ResourceManager.GetString("NotificationFormat_RemoveDuplicateLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Emails removed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotificationFormat_RemoveEmails {
            get {
                return ResourceManager.GetString("NotificationFormat_RemoveEmails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   HTML tags removed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotificationFormat_RemoveHtmlTags {
            get {
                return ResourceManager.GetString("NotificationFormat_RemoveHtmlTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Punctuation removed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotificationFormat_RemovePunctuation {
            get {
                return ResourceManager.GetString("NotificationFormat_RemovePunctuation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   URLs removed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotificationFormat_RemoveUrls {
            get {
                return ResourceManager.GetString("NotificationFormat_RemoveUrls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Markdown links stripped に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotificationFormat_StripMarkdownLinks {
            get {
                return ResourceManager.GetString("NotificationFormat_StripMarkdownLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Converted to camelCase に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotificationFormat_ToCamelCase {
            get {
                return ResourceManager.GetString("NotificationFormat_ToCamelCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Converted to lower case に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotificationFormat_ToLower {
            get {
                return ResourceManager.GetString("NotificationFormat_ToLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Converted to PascalCase に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotificationFormat_ToPascalCase {
            get {
                return ResourceManager.GetString("NotificationFormat_ToPascalCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Converted to title case に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotificationFormat_ToTitleCase {
            get {
                return ResourceManager.GetString("NotificationFormat_ToTitleCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Converted to upper case に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotificationFormat_ToUpper {
            get {
                return ResourceManager.GetString("NotificationFormat_ToUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Trimmed whitespace に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotificationFormat_Trim {
            get {
                return ResourceManager.GetString("NotificationFormat_Trim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Text truncated に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotificationFormat_Truncate {
            get {
                return ResourceManager.GetString("NotificationFormat_Truncate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Whitespace normalized に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotificationFormat_WhitespaceNormalized {
            get {
                return ResourceManager.GetString("NotificationFormat_WhitespaceNormalized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Notification Margin: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotificationMargin {
            get {
                return ResourceManager.GetString("NotificationMargin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Max Height: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotificationMaxHeight {
            get {
                return ResourceManager.GetString("NotificationMaxHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Max Width: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotificationMaxWidth {
            get {
                return ResourceManager.GetString("NotificationMaxWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Min Height: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotificationMinHeight {
            get {
                return ResourceManager.GetString("NotificationMinHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Min Width: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotificationMinWidth {
            get {
                return ResourceManager.GetString("NotificationMinWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Notification Offset X: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotificationOffsetX {
            get {
                return ResourceManager.GetString("NotificationOffsetX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Notification Offset Y: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotificationOffsetY {
            get {
                return ResourceManager.GetString("NotificationOffsetY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OpenSetting {
            get {
                return ResourceManager.GetString("OpenSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Processing Mode: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProcessingMode {
            get {
                return ResourceManager.GetString("ProcessingMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Collapse Whitespace に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProcessingModeDisplay_CollapseWhitespace {
            get {
                return ResourceManager.GetString("ProcessingModeDisplay_CollapseWhitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Convert Tabs to Spaces に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProcessingModeDisplay_ConvertTabsToSpaces {
            get {
                return ResourceManager.GetString("ProcessingModeDisplay_ConvertTabsToSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Join Lines with Space に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProcessingModeDisplay_JoinLinesWithSpace {
            get {
                return ResourceManager.GetString("ProcessingModeDisplay_JoinLinesWithSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No Processing に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProcessingModeDisplay_None {
            get {
                return ResourceManager.GetString("ProcessingModeDisplay_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Normalize Unicode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProcessingModeDisplay_NormalizeUnicode {
            get {
                return ResourceManager.GetString("ProcessingModeDisplay_NormalizeUnicode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Normalize Whitespace に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProcessingModeDisplay_NormalizeWhitespace {
            get {
                return ResourceManager.GetString("ProcessingModeDisplay_NormalizeWhitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove Control Characters に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProcessingModeDisplay_RemoveControlCharacters {
            get {
                return ResourceManager.GetString("ProcessingModeDisplay_RemoveControlCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove Diacritics に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProcessingModeDisplay_RemoveDiacritics {
            get {
                return ResourceManager.GetString("ProcessingModeDisplay_RemoveDiacritics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove Duplicate Lines に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProcessingModeDisplay_RemoveDuplicateLines {
            get {
                return ResourceManager.GetString("ProcessingModeDisplay_RemoveDuplicateLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove Emails に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProcessingModeDisplay_RemoveEmails {
            get {
                return ResourceManager.GetString("ProcessingModeDisplay_RemoveEmails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove HTML Tags に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProcessingModeDisplay_RemoveHtmlTags {
            get {
                return ResourceManager.GetString("ProcessingModeDisplay_RemoveHtmlTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove Line Breaks に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProcessingModeDisplay_RemoveLineBreaks {
            get {
                return ResourceManager.GetString("ProcessingModeDisplay_RemoveLineBreaks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove Punctuation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProcessingModeDisplay_RemovePunctuation {
            get {
                return ResourceManager.GetString("ProcessingModeDisplay_RemovePunctuation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove URLs に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProcessingModeDisplay_RemoveUrls {
            get {
                return ResourceManager.GetString("ProcessingModeDisplay_RemoveUrls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Strip Markdown Links に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProcessingModeDisplay_StripMarkdownLinks {
            get {
                return ResourceManager.GetString("ProcessingModeDisplay_StripMarkdownLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Convert to camelCase に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProcessingModeDisplay_ToCamelCase {
            get {
                return ResourceManager.GetString("ProcessingModeDisplay_ToCamelCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Convert to Lower Case に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProcessingModeDisplay_ToLower {
            get {
                return ResourceManager.GetString("ProcessingModeDisplay_ToLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Convert to PascalCase に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProcessingModeDisplay_ToPascalCase {
            get {
                return ResourceManager.GetString("ProcessingModeDisplay_ToPascalCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Convert to Title Case に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProcessingModeDisplay_ToTitleCase {
            get {
                return ResourceManager.GetString("ProcessingModeDisplay_ToTitleCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Convert to Upper Case に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProcessingModeDisplay_ToUpper {
            get {
                return ResourceManager.GetString("ProcessingModeDisplay_ToUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Trim Whitespace に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProcessingModeDisplay_Trim {
            get {
                return ResourceManager.GetString("ProcessingModeDisplay_Trim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Truncate Text に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProcessingModeDisplay_Truncate {
            get {
                return ResourceManager.GetString("ProcessingModeDisplay_Truncate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SaveText {
            get {
                return ResourceManager.GetString("SaveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Setting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingTitle {
            get {
                return ResourceManager.GetString("SettingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show copy notification: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShowCopyNotification {
            get {
                return ResourceManager.GetString("ShowCopyNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show operation notification: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShowOperationNotification {
            get {
                return ResourceManager.GetString("ShowOperationNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ClipboardUtility - Clipboard Utility に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
    }
}
