//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClipboardUtility.src.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClipboardUtility.src.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Actions に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ActionsText {
            get {
                return ResourceManager.GetString("ActionsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1. Place this folder wherever you like.
        ///2. Create a shortcut for `Clipboard Utility.exe`.
        ///3. Place the created shortcut into the Startup folder.
        ///
        ///*How to open the Startup folder:* Press the Windows key and the R key simultaneously. Type `shell:startup` and press Enter. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AddStartUpGuidanceManuallyText {
            get {
                return ResourceManager.GetString("AddStartUpGuidanceManuallyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   How to execute this software when computer starts. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AddStartUpGuidanceManuallyTitle {
            get {
                return ResourceManager.GetString("AddStartUpGuidanceManuallyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This app is Clipboard Utility tool. It help you counting characters and processing text. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AppDescription {
            get {
                return ResourceManager.GetString("AppDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Apply に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ApplyText {
            get {
                return ResourceManager.GetString("ApplyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clipboard Utility に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   v0.5.1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AppVersion {
            get {
                return ResourceManager.GetString("AppVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CancelText {
            get {
                return ResourceManager.GetString("CancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Characters に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CharacterCountText {
            get {
                return ResourceManager.GetString("CharacterCountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clear に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ClearText {
            get {
                return ResourceManager.GetString("ClearText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clipboard Access was Denied に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ClipboardAccessDeniedMessage {
            get {
                return ResourceManager.GetString("ClipboardAccessDeniedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clipboard Manager に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ClipboardManagerTitle {
            get {
                return ResourceManager.GetString("ClipboardManagerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clipboard Preview に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ClipboardPreviewText {
            get {
                return ResourceManager.GetString("ClipboardPreviewText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CloseText {
            get {
                return ResourceManager.GetString("CloseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy to Clipboard に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CopyToClipboardText {
            get {
                return ResourceManager.GetString("CopyToClipboardText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Deletetext {
            get {
                return ResourceManager.GetString("Deletetext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EditText {
            get {
                return ResourceManager.GetString("EditText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   General に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GeneralText {
            get {
                return ResourceManager.GetString("GeneralText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Language に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LanguageSettingTitle {
            get {
                return ResourceManager.GetString("LanguageSettingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This software uses the following third-party software and fonts. Below are their required licenses and copyright notices. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LicenseDescription {
            get {
                return ResourceManager.GetString("LicenseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LICENSE に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LicenseText {
            get {
                return ResourceManager.GetString("LicenseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lines に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LineCountText {
            get {
                return ResourceManager.GetString("LineCountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Don&apos;t show again に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NeverShowAgainText {
            get {
                return ResourceManager.GetString("NeverShowAgainText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NewText {
            get {
                return ResourceManager.GetString("NewText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No clipboard data に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NoClipboardDataText {
            get {
                return ResourceManager.GetString("NoClipboardDataText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   NotificationDuration に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotificationDurationTitle {
            get {
                return ResourceManager.GetString("NotificationDurationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Whitespace collapsed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotificationFormat_CollapseWhitespace {
            get {
                return ResourceManager.GetString("NotificationFormat_CollapseWhitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All whiteSpace removed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotificationFormat_CollapseWhitespaceAll {
            get {
                return ResourceManager.GetString("NotificationFormat_CollapseWhitespaceAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tabs converted to spaces に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotificationFormat_ConvertTabsToSpaces {
            get {
                return ResourceManager.GetString("NotificationFormat_ConvertTabsToSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copied {0} characters に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotificationFormat_CopiedWords {
            get {
                return ResourceManager.GetString("NotificationFormat_CopiedWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lines joined with spaces に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotificationFormat_JoinLinesWithSpace {
            get {
                return ResourceManager.GetString("NotificationFormat_JoinLinesWithSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Line breaks removed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotificationFormat_LineBreakRemoved {
            get {
                return ResourceManager.GetString("NotificationFormat_LineBreakRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Text normalized に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotificationFormat_NormalizeUnicode {
            get {
                return ResourceManager.GetString("NotificationFormat_NormalizeUnicode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Control characters removed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotificationFormat_RemoveControlChars {
            get {
                return ResourceManager.GetString("NotificationFormat_RemoveControlChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Diacritics removed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotificationFormat_RemoveDiacritics {
            get {
                return ResourceManager.GetString("NotificationFormat_RemoveDiacritics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Duplicate lines removed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotificationFormat_RemoveDuplicateLines {
            get {
                return ResourceManager.GetString("NotificationFormat_RemoveDuplicateLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Emails removed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotificationFormat_RemoveEmails {
            get {
                return ResourceManager.GetString("NotificationFormat_RemoveEmails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   HTML tags removed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotificationFormat_RemoveHtmlTags {
            get {
                return ResourceManager.GetString("NotificationFormat_RemoveHtmlTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Punctuation removed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotificationFormat_RemovePunctuation {
            get {
                return ResourceManager.GetString("NotificationFormat_RemovePunctuation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   URLs removed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotificationFormat_RemoveUrls {
            get {
                return ResourceManager.GetString("NotificationFormat_RemoveUrls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Markdown links stripped に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotificationFormat_StripMarkdownLinks {
            get {
                return ResourceManager.GetString("NotificationFormat_StripMarkdownLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Converted to camelCase に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotificationFormat_ToCamelCase {
            get {
                return ResourceManager.GetString("NotificationFormat_ToCamelCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Converted to lower case に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotificationFormat_ToLower {
            get {
                return ResourceManager.GetString("NotificationFormat_ToLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Converted to PascalCase に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotificationFormat_ToPascalCase {
            get {
                return ResourceManager.GetString("NotificationFormat_ToPascalCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Converted to title case に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotificationFormat_ToTitleCase {
            get {
                return ResourceManager.GetString("NotificationFormat_ToTitleCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Converted to upper case に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotificationFormat_ToUpper {
            get {
                return ResourceManager.GetString("NotificationFormat_ToUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Trimmed whitespace に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotificationFormat_Trim {
            get {
                return ResourceManager.GetString("NotificationFormat_Trim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Text truncated に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotificationFormat_Truncate {
            get {
                return ResourceManager.GetString("NotificationFormat_Truncate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Whitespace normalized に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotificationFormat_WhitespaceNormalized {
            get {
                return ResourceManager.GetString("NotificationFormat_WhitespaceNormalized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Notification Margin: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotificationMargin {
            get {
                return ResourceManager.GetString("NotificationMargin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Max Height に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotificationMaxHeight {
            get {
                return ResourceManager.GetString("NotificationMaxHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Max Width に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotificationMaxWidth {
            get {
                return ResourceManager.GetString("NotificationMaxWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Min Height に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotificationMinHeight {
            get {
                return ResourceManager.GetString("NotificationMinHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Min Width に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotificationMinWidth {
            get {
                return ResourceManager.GetString("NotificationMinWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Notification Offset X に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotificationOffsetX {
            get {
                return ResourceManager.GetString("NotificationOffsetX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Notification Offset Y: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotificationOffsetY {
            get {
                return ResourceManager.GetString("NotificationOffsetY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Notification に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotificationText {
            get {
                return ResourceManager.GetString("NotificationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Setting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OpenSetting {
            get {
                return ResourceManager.GetString("OpenSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ・Right-clicking the taskbar icon opens the menu.
        ///・Clicking the taskbar icon performs a string operation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OperationGuidanceText {
            get {
                return ResourceManager.GetString("OperationGuidanceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Normalizes all whitespace including full-width and half-width spaces に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Preset_NormalizeWhitespace_Description {
            get {
                return ResourceManager.GetString("Preset_NormalizeWhitespace_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Removes all line breaks and replaces them with spaces に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Preset_RemoveLineBreaks_Description {
            get {
                return ResourceManager.GetString("Preset_RemoveLineBreaks_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove Line Breaks(Built-in) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Preset_RemoveLineBreaks_Name {
            get {
                return ResourceManager.GetString("Preset_RemoveLineBreaks_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove Line Breaks and Normalize Whitespace(Built-in) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Preset_RemoveLineBreaksAndNormalizeWhitespace_Name {
            get {
                return ResourceManager.GetString("Preset_RemoveLineBreaksAndNormalizeWhitespace_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Preset for tray click: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PresetForTrayClickTitle {
            get {
                return ResourceManager.GetString("PresetForTrayClickTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Presets に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PresetsText {
            get {
                return ResourceManager.GetString("PresetsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select a processing mode and click Apply to transform the text. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProcessingInfoText {
            get {
                return ResourceManager.GetString("ProcessingInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Processing Mode: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProcessingMode {
            get {
                return ResourceManager.GetString("ProcessingMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Collapse Whitespace に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProcessingModeDisplay_CollapseWhitespace {
            get {
                return ResourceManager.GetString("ProcessingModeDisplay_CollapseWhitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Convert Tabs to Spaces に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProcessingModeDisplay_ConvertTabsToSpaces {
            get {
                return ResourceManager.GetString("ProcessingModeDisplay_ConvertTabsToSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Join Lines with Space に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProcessingModeDisplay_JoinLinesWithSpace {
            get {
                return ResourceManager.GetString("ProcessingModeDisplay_JoinLinesWithSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No Processing に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProcessingModeDisplay_None {
            get {
                return ResourceManager.GetString("ProcessingModeDisplay_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Normalize Unicode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProcessingModeDisplay_NormalizeUnicode {
            get {
                return ResourceManager.GetString("ProcessingModeDisplay_NormalizeUnicode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Normalize Whitespace に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProcessingModeDisplay_NormalizeWhitespace {
            get {
                return ResourceManager.GetString("ProcessingModeDisplay_NormalizeWhitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove Control Characters に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProcessingModeDisplay_RemoveControlCharacters {
            get {
                return ResourceManager.GetString("ProcessingModeDisplay_RemoveControlCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove Diacritics に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProcessingModeDisplay_RemoveDiacritics {
            get {
                return ResourceManager.GetString("ProcessingModeDisplay_RemoveDiacritics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove Duplicate Lines に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProcessingModeDisplay_RemoveDuplicateLines {
            get {
                return ResourceManager.GetString("ProcessingModeDisplay_RemoveDuplicateLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove Emails に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProcessingModeDisplay_RemoveEmails {
            get {
                return ResourceManager.GetString("ProcessingModeDisplay_RemoveEmails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove HTML Tags に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProcessingModeDisplay_RemoveHtmlTags {
            get {
                return ResourceManager.GetString("ProcessingModeDisplay_RemoveHtmlTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove Line Breaks に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProcessingModeDisplay_RemoveLineBreaks {
            get {
                return ResourceManager.GetString("ProcessingModeDisplay_RemoveLineBreaks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove Punctuation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProcessingModeDisplay_RemovePunctuation {
            get {
                return ResourceManager.GetString("ProcessingModeDisplay_RemovePunctuation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove URLs に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProcessingModeDisplay_RemoveUrls {
            get {
                return ResourceManager.GetString("ProcessingModeDisplay_RemoveUrls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Strip Markdown Links に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProcessingModeDisplay_StripMarkdownLinks {
            get {
                return ResourceManager.GetString("ProcessingModeDisplay_StripMarkdownLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Convert to camelCase に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProcessingModeDisplay_ToCamelCase {
            get {
                return ResourceManager.GetString("ProcessingModeDisplay_ToCamelCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Convert to Lower Case に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProcessingModeDisplay_ToLower {
            get {
                return ResourceManager.GetString("ProcessingModeDisplay_ToLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Convert to PascalCase に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProcessingModeDisplay_ToPascalCase {
            get {
                return ResourceManager.GetString("ProcessingModeDisplay_ToPascalCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Convert to Title Case に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProcessingModeDisplay_ToTitleCase {
            get {
                return ResourceManager.GetString("ProcessingModeDisplay_ToTitleCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Convert to Upper Case に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProcessingModeDisplay_ToUpper {
            get {
                return ResourceManager.GetString("ProcessingModeDisplay_ToUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Trim Whitespace に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProcessingModeDisplay_Trim {
            get {
                return ResourceManager.GetString("ProcessingModeDisplay_Trim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Truncate Text に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProcessingModeDisplay_Truncate {
            get {
                return ResourceManager.GetString("ProcessingModeDisplay_Truncate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Refresh に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RefreshText {
            get {
                return ResourceManager.GetString("RefreshText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Run at startup に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RunAtStartupText {
            get {
                return ResourceManager.GetString("RunAtStartupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SaveText {
            get {
                return ResourceManager.GetString("SaveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select Mode: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SelectProcessingModeText {
            get {
                return ResourceManager.GetString("SelectProcessingModeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Some setting items will be reflected to reopen settings or restart app. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingInfomationText {
            get {
                return ResourceManager.GetString("SettingInfomationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Setting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingTitle {
            get {
                return ResourceManager.GetString("SettingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show copy notification: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShowCopyNotification {
            get {
                return ResourceManager.GetString("ShowCopyNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show operation notification: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShowOperationNotification {
            get {
                return ResourceManager.GetString("ShowOperationNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TaskTray Action に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TaskTrayClickOperationText {
            get {
                return ResourceManager.GetString("TaskTrayClickOperationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Text Processing に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextProcessingText {
            get {
                return ResourceManager.GetString("TextProcessingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use Presets に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UsePresetsText {
            get {
                return ResourceManager.GetString("UsePresetsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WelcomeNotificationCloseText {
            get {
                return ResourceManager.GetString("WelcomeNotificationCloseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ClipboardUtility - Clipboard Utility に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Words に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WordCountText {
            get {
                return ResourceManager.GetString("WordCountText", resourceCulture);
            }
        }
    }
}
