using ClipboardUtility.src.Properties;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.CompilerServices;

namespace ClipboardUtility.src.Helpers;

// リソースの公開ラッパー（動的切替対応）
public sealed class LocalizedStrings : INotifyPropertyChanged
{
    public static LocalizedStrings Instance { get; } = new LocalizedStrings();

    public event PropertyChangedEventHandler? PropertyChanged;

    private LocalizedStrings() { }

    public string SettingTitle => Resources.SettingTitle;
    public string WindowTitle => Resources.WindowTitle;
    public string NotificationFormat_CopiedWords => Resources.NotificationFormat_CopiedWords;
    public string NotificationFormat_LineBreakRemoved => Resources.NotificationFormat_LineBreakRemoved;
    public string NotificationFormat_WhitespaceNormalized => Resources.NotificationFormat_WhitespaceNormalized;
    public string NotificationFormat_NormalizeUnicode => Resources.NotificationFormat_NormalizeUnicode;
    public string NotificationFormat_RemoveDiacritics => Resources.NotificationFormat_RemoveDiacritics;
    public string NotificationFormat_RemovePunctuation => Resources.NotificationFormat_RemovePunctuation;
    public string NotificationFormat_RemoveControlChars => Resources.NotificationFormat_RemoveControlChars;
    public string NotificationFormat_RemoveUrls => Resources.NotificationFormat_RemoveUrls;
    public string NotificationFormat_RemoveEmails => Resources.NotificationFormat_RemoveEmails;
    public string NotificationFormat_RemoveHtmlTags => Resources.NotificationFormat_RemoveHtmlTags;
    public string NotificationFormat_StripMarkdownLinks => Resources.NotificationFormat_StripMarkdownLinks;
    public string NotificationFormat_ConvertTabsToSpaces => Resources.NotificationFormat_ConvertTabsToSpaces;
    public string NotificationFormat_Trim => Resources.NotificationFormat_Trim;
    public string NotificationFormat_ToUpper => Resources.NotificationFormat_ToUpper;
    public string NotificationFormat_ToLower => Resources.NotificationFormat_ToLower;
    public string NotificationFormat_ToTitleCase => Resources.NotificationFormat_ToTitleCase;
    public string NotificationFormat_ToPascalCase => Resources.NotificationFormat_ToPascalCase;
    public string NotificationFormat_ToCamelCase => Resources.NotificationFormat_ToCamelCase;
    public string NotificationFormat_Truncate => Resources.NotificationFormat_Truncate;
    public string NotificationFormat_JoinLinesWithSpace => Resources.NotificationFormat_JoinLinesWithSpace;
    public string NotificationFormat_RemoveDuplicateLines => Resources.NotificationFormat_RemoveDuplicateLines;
    public string NotificationFormat_CollapseWhitespace => Resources.NotificationFormat_CollapseWhitespace;
    public string NotificationFormat_CollapseWhitespaceAll => Resources.NotificationFormat_CollapseWhitespaceAll;
    public string SaveText => Resources.SaveText;
    public string CancelText => Resources.CancelText;
    public string ShowCopyNotificationTitle => Resources.ShowCopyNotification;
    public string ShowOperationNotificationTitle => Resources.ShowOperationNotification;
    public string ProcessingModeTitle => Resources.ProcessingMode;
    public string NotificationOffsetXTitle => Resources.NotificationOffsetX;
    public string NotificationOffsetYTitle => Resources.NotificationOffsetY;
    public string NotificationMarginTitle => Resources.NotificationMargin;
    public string NotificationMinWidthTitle => Resources.NotificationMinWidth;
    public string NotificationMaxWidthTitle => Resources.NotificationMaxWidth;
    public string NotificationMinHeightTitle => Resources.NotificationMinHeight;
    public string NotificationMaxHeightTitle => Resources.NotificationMaxHeight;
    public string ShowCopyNotification => Resources.ShowCopyNotification;
    public string ShowOperationNotification => Resources.ShowOperationNotification;
    public string ProcessingMode => Resources.ProcessingMode;
    public string OpenSettingText => Resources.OpenSetting;
    public string ExitText => Resources.Exit;
    public string NotificationDurationTitle => Resources.NotificationDurationTitle;
    public string ClipboardAccessDeniedMessage => Resources.ClipboardAccessDeniedMessage;
    public string AppTitle => Resources.AppTitle;
    public string AppVersion => Resources.AppVersion;
    public string AppDescription => Resources.AppDescription;
    public string WelcomeNotificationCloseText => Resources.WelcomeNotificationCloseText;
    public string NeverShowAgainText => Resources.NeverShowAgainText;
    public string OperationGuidanceText => Resources.OperationGuidanceText;
    public string LanugageSettingTitle => Resources.LanguageSettingTitle;
    public string SettingInfomationText => Resources.SettingInfomationText;
    public string LicenseDescription => Resources.LicenseDescription;
    public string AddStartUpGuidanceManuallyText => Resources.AddStartUpGuidanceManuallyText;
    public string AddStartUpGuidanceManuallyTitle => Resources.AddStartUpGuidanceManuallyTitle;
    public string NoClipboardDataText => Resources.NoClipboardDataText;
    public string CharacterCountText => Resources.CharacterCountText;
    public string WordCountText => Resources.WordCountText;
    public string LineCountText => Resources.LineCountText;
    public string ClipboardManagerTitle => Resources.ClipboardManagerTitle;
    public string ClipboardPreviewText => Resources.ClipboardPreviewText;
    public string TextProcessingText => Resources.TextProcessingText;
    public string SelectProcessingModeText => Resources.SelectProcessingModeText;
    public string ApplyText => Resources.ApplyText;
    public string ProcessingInfoText => Resources.ProcessingInfoText;
    public string ActionsText => Resources.ActionsText;
    public string CopyToClipboardText => Resources.CopyToClipboardText;
    public string RefreshText => Resources.RefreshText;
    public string ClearText => Resources.ClearText;
    public string CloseText => Resources.CloseText;
    public string NewText => Resources.NewText;
    public string EditText => Resources.EditText;
    public string DeleteText => Resources.Deletetext;
    public string GeneralText => Resources.GeneralText;
    public string PresetsText => Resources.PresetsText;
    public string UsePresetsText => Resources.ResourceManager.GetString("UsePresetsText", CultureInfo.CurrentUICulture) ?? "Use Presets";
    public string PresetForTrayClickTitle => Resources.ResourceManager.GetString("PresetForTrayClickTitle", CultureInfo.CurrentUICulture) ?? "Preset for tray click:";
    public string NotificationText => Resources.ResourceManager.GetString("NotificationText", CultureInfo.CurrentUICulture) ?? "Notification";
    public string LicenseText => Resources.ResourceManager.GetString("LicenseText", CultureInfo.CurrentUICulture) ?? "LICENSE";
    public string TaskTrayClickOperationText => Resources.TaskTrayClickOperationText;
    public string CheckForUpdatesText => Resources.ResourceManager.GetString("CheckForUpdatesText", CultureInfo.CurrentUICulture) ?? "Check for Updates";
    public string UpdateCheckInProgressText => Resources.ResourceManager.GetString("UpdateCheckInProgressText", CultureInfo.CurrentUICulture) ?? "Checking for updates...";
    public string UpdateAvailableText => Resources.ResourceManager.GetString("UpdateAvailableText", CultureInfo.CurrentUICulture) ?? "Update Available!";
    public string UpdateAvailableMessageText => Resources.ResourceManager.GetString("UpdateAvailableMessageText", CultureInfo.CurrentUICulture) ?? "A new version ({0}) is available. Current version: {1}\n\nWould you like to visit the download page?";
    public string NoUpdateAvailableText => Resources.ResourceManager.GetString("NoUpdateAvailableText", CultureInfo.CurrentUICulture) ?? "No Update Available";
    public string NoUpdateAvailableMessageText => Resources.ResourceManager.GetString("NoUpdateAvailableMessageText", CultureInfo.CurrentUICulture) ?? "You are using the latest version ({0}).";
    public string UpdateCheckFailedText => Resources.ResourceManager.GetString("UpdateCheckFailedText", CultureInfo.CurrentUICulture) ?? "Update Check Failed";
    public string UpdateCheckFailedMessageText => Resources.ResourceManager.GetString("UpdateCheckFailedMessageText", CultureInfo.CurrentUICulture) ?? "Failed to check for updates. Please check your internet connection and try again.";
    public string CurrentVersionText => Resources.ResourceManager.GetString("CurrentVersionText", CultureInfo.CurrentUICulture) ?? "Current Version:";
    public string BackButtonText => Resources.ResourceManager.GetString("BackButtonText", CultureInfo.CurrentUICulture) ?? "Back";
    public string NextButtonText => Resources.ResourceManager.GetString("NextButtonText", CultureInfo.CurrentUICulture) ?? "Next";
    public string WelcomePresetSettingTitle => Resources.ResourceManager.GetString("WelcomePresetSettingTitle", CultureInfo.CurrentUICulture) ?? "Welcome Preset Setting";


    public void ChangeCulture(CultureInfo culture)
    {
        if (culture == null) throw new ArgumentNullException(nameof(culture));
        CultureInfo.CurrentUICulture = culture;
        // 各プロパティ名で通知（簡易）
        OnPropertyChanged(nameof(SettingTitle));
        OnPropertyChanged(nameof(WindowTitle));
        OnPropertyChanged(nameof(NotificationFormat_CopiedWords));
        OnPropertyChanged(nameof(NotificationFormat_LineBreakRemoved));
        OnPropertyChanged(nameof(NotificationFormat_WhitespaceNormalized));
        OnPropertyChanged(nameof(NotificationFormat_NormalizeUnicode));
        OnPropertyChanged(nameof(NotificationFormat_RemoveDiacritics));
        OnPropertyChanged(nameof(NotificationFormat_RemovePunctuation));
        OnPropertyChanged(nameof(NotificationFormat_RemoveControlChars));
        OnPropertyChanged(nameof(NotificationFormat_RemoveUrls));
        OnPropertyChanged(nameof(NotificationFormat_RemoveEmails));
        OnPropertyChanged(nameof(NotificationFormat_RemoveHtmlTags));
        OnPropertyChanged(nameof(NotificationFormat_StripMarkdownLinks));
        OnPropertyChanged(nameof(NotificationFormat_ConvertTabsToSpaces));
        OnPropertyChanged(nameof(NotificationFormat_Trim));
        OnPropertyChanged(nameof(NotificationFormat_ToUpper));
        OnPropertyChanged(nameof(NotificationFormat_ToLower));
        OnPropertyChanged(nameof(NotificationFormat_ToTitleCase));
        OnPropertyChanged(nameof(NotificationFormat_ToPascalCase));
        OnPropertyChanged(nameof(NotificationFormat_ToCamelCase));
        OnPropertyChanged(nameof(NotificationFormat_Truncate));
        OnPropertyChanged(nameof(NotificationFormat_JoinLinesWithSpace));
        OnPropertyChanged(nameof(NotificationFormat_RemoveDuplicateLines));
        OnPropertyChanged(nameof(NotificationFormat_CollapseWhitespace));
        OnPropertyChanged(nameof(NotificationFormat_CollapseWhitespaceAll));
        OnPropertyChanged(nameof(SaveText));
        OnPropertyChanged(nameof(CancelText));
        OnPropertyChanged(nameof(ShowCopyNotificationTitle));
        OnPropertyChanged(nameof(ShowOperationNotificationTitle));
        OnPropertyChanged(nameof(ProcessingModeTitle));
        OnPropertyChanged(nameof(NotificationOffsetXTitle));
        OnPropertyChanged(nameof(NotificationOffsetYTitle));
        OnPropertyChanged(nameof(NotificationMarginTitle));
        OnPropertyChanged(nameof(NotificationMinWidthTitle));
        OnPropertyChanged(nameof(NotificationMaxWidthTitle));
        OnPropertyChanged(nameof(NotificationMinHeightTitle));
        OnPropertyChanged(nameof(NotificationMaxHeightTitle));
        OnPropertyChanged(nameof(ShowCopyNotification));
        OnPropertyChanged(nameof(ShowOperationNotification));
        OnPropertyChanged(nameof(ProcessingMode));
        OnPropertyChanged(nameof(OpenSettingText));
        OnPropertyChanged(nameof(ExitText));
        OnPropertyChanged(nameof(NotificationDurationTitle));
        OnPropertyChanged(nameof(ClipboardAccessDeniedMessage));
        OnPropertyChanged(nameof(AppDescription));
        OnPropertyChanged(nameof(WelcomeNotificationCloseText));
        OnPropertyChanged(nameof(NeverShowAgainText));
        OnPropertyChanged(nameof(OperationGuidanceText));
        OnPropertyChanged(nameof(LanugageSettingTitle));
        OnPropertyChanged(nameof(SettingInfomationText));
        OnPropertyChanged(nameof(LicenseDescription));
        OnPropertyChanged(nameof(AddStartUpGuidanceManuallyText));
        OnPropertyChanged(nameof(AddStartUpGuidanceManuallyTitle));
        OnPropertyChanged(nameof(NoClipboardDataText));
        OnPropertyChanged(nameof(CharacterCountText));
        OnPropertyChanged(nameof(WordCountText));
        OnPropertyChanged(nameof(LineCountText));
        OnPropertyChanged(nameof(ClipboardManagerTitle));
        OnPropertyChanged(nameof(ClipboardPreviewText));
        OnPropertyChanged(nameof(TextProcessingText));
        OnPropertyChanged(nameof(SelectProcessingModeText));
        OnPropertyChanged(nameof(ApplyText));
        OnPropertyChanged(nameof(ProcessingInfoText));
        OnPropertyChanged(nameof(ActionsText));
        OnPropertyChanged(nameof(CopyToClipboardText));
        OnPropertyChanged(nameof(RefreshText));
        OnPropertyChanged(nameof(ClearText));
        OnPropertyChanged(nameof(CloseText));
        OnPropertyChanged(nameof(NewText));
        OnPropertyChanged(nameof(EditText));
        OnPropertyChanged(nameof(DeleteText));
        OnPropertyChanged(nameof(GeneralText));
        OnPropertyChanged(nameof(PresetsText));
        OnPropertyChanged(nameof(TaskTrayClickOperationText));
        OnPropertyChanged(nameof(CheckForUpdatesText));
        OnPropertyChanged(nameof(UpdateCheckInProgressText));
        OnPropertyChanged(nameof(UpdateAvailableText));
        OnPropertyChanged(nameof(UpdateAvailableMessageText));
        OnPropertyChanged(nameof(NoUpdateAvailableText));
        OnPropertyChanged(nameof(NoUpdateAvailableMessageText));
        OnPropertyChanged(nameof(UpdateCheckFailedText));
        OnPropertyChanged(nameof(UpdateCheckFailedMessageText));
        OnPropertyChanged(nameof(CurrentVersionText));
        OnPropertyChanged(nameof(BackButtonText));
        OnPropertyChanged(nameof(NextButtonText));
        OnPropertyChanged(nameof(WelcomePresetSettingTitle));
    }

    private void OnPropertyChanged([CallerMemberName] string? name = null)
        => PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(name));
}